### ISSUE TITLE
Props is not allowed

### ISSUE THREAD

**Issue by thgh** [bothrs/eslint-config#12]
This rule leaves broken code behind.

<img width="256" alt="Screenshot 2022-01-18 at 14 56 49" src="https://user-images.githubusercontent.com/1109982/149950940-d0758371-3637-47bd-b1d2-eb577df754bb.png">

**Comment by FabianMeul** [comment]
What rule does this refer to?
It should be configured to allow "props", but this might also be fixed by removing the "disallowed abbreviations" rule? 🤔

**Comment by thgh** [comment]
the `abbreviations` rule is the culprit indeed, there were also other cases where the automated fix broke stuff.

**Comment by FabianMeul** [comment]
Resolved in https://github.com/bothrs/eslint-config/pull/13
