### ISSUE TITLE
installing it in a project gives a dependency issue with unicorn

### ISSUE THREAD

**Issue by JaccoGoris** [bothrs/eslint-config#17]
Uncaught exception received.
Error: Failed to load plugin 'unicorn' declared in '.eslintrc.js » @bothrs/eslint-config': Cannot find module 'eslint/use-at-your-own-risk'
Require stack:
- /Users/.../node_modules/eslint-plugin-unicorn/rules/utils/get-builtin-rule.js
- /Users/.../node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js
- /Users/.../node_modules/eslint-plugin-unicorn/rules/utils/rule.js
- /Users/.../node_modules/eslint-plugin-unicorn/index.js
- /Users/.../node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /Users/.../node_modules/@eslint/eslintrc/lib/index.js
- /Users/.../node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/.../node_modules/eslint/lib/cli-engine/index.js
- /Users/.../node_modules/eslint/lib/api.js
- /Users/jacco/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js
Referenced from: /Users/.../node_modules/@bothrs/eslint-config/index.js

**Comment by JaccoGoris** [comment]
`{
  "name": "...",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "doppler run -- yarn next:dev",
    "dev:prd": "doppler run -c prd -- yarn next:dev",
    "next:dev": "NODE_OPTIONS='--inspect' next dev",
    "build": "next build",
    "start": "next start -p 8080",
    "test": "jest --watchAll"
  },
  "repository": {
    "type": "git",
    "url": "..."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "..."
  },
  "homepage": "...",
  "dependencies": {
    "@sendgrid/mail": "^7.4.2",
    "@sentry/nextjs": "^6.3.5",
    "@types/jest": "^26.0.20",
    "@types/next": "^9.0.0",
    "@types/react": "^17.0.3",
    "airtable": "^0.10.1",
    "array-move": "^3.0.1",
    "axios": "^0.27.2",
    "axios-cache-adapter": "^2.7.3",
    "cookie": "^0.4.1",
    "cors": "^2.8.5",
    "csv-parser": "^3.0.0",
    "dayjs": "^1.10.4",
    "firebase": "^8.3.0",
    "firebase-admin": "^9.6.0",
    "form-data": "^4.0.0",
    "image-to-base64": "^2.1.1",
    "immer": "^9.0.6",
    "jest": "^26.6.3",
    "moment": "^2.29.1",
    "monk": "^7.3.3",
    "next": "^10.0.8",
    "node-fetch": "^2.6.1",
    "node-persist": "^3.1.0",
    "pdf-creator-node": "^2.2.2",
    "react": "^17.0.1",
    "react-cookie": "^4.0.3",
    "react-cropper": "^2.1.7",
    "react-dom": "^17.0.1",
    "react-dropzone": "^11.3.1",
    "react-firebase-hooks": "^3.0.2",
    "react-gtm-module": "^2.0.11",
    "react-modal": "^3.12.1",
    "react-sortable-hoc": "^1.11.0",
    "react-table": "^7.6.3",
    "react-tooltip": "^4.2.21",
    "shopify-api-node": "^3.6.5",
    "styled-components": "^5.2.1",
    "ts-jest": "^26.5.3",
    "uuid": "^8.3.2",
    "zustand": "^3.3.3"
  },
  "devDependencies": {
    "@bothrs/eslint-config": "^1.6.1",
    "@types/cookie": "^0.4.0",
    "@types/gtag.js": "^0.0.8",
    "@types/node": "^14.14.33",
    "@types/node-persist": "^3.1.2",
    "babel-plugin-styled-components": "^1.12.0",
    "eslint": "^7.22.0",
    "typescript": "^4.2.3"
  }
}
`

**Comment by FabianMeul** [comment]
As v2 is released with revamped dependency handling;

Could you re-check if this issue is still there?
